# Generated by Django 4.0.2 on 2022-04-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('stud_class', models.CharField(max_length=100)),
                ('attendance', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('teach_username', models.CharField(max_length=100)),
                ('atten_date', models.DateField()),
            ],
        ),
    ]
