# Generated by Django 4.0.2 on 2022-04-15 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminUser', '0002_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='stud_class',
        ),
    ]
