# Generated by Django 4.0.2 on 2022-04-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminUser', '0003_remove_attendance_stud_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='roll_no',
            new_name='stud_id',
        ),
    ]
