# Generated by Django 4.0.2 on 2022-04-15 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminUser', '0005_alter_attendance_stud_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='stud_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atten', to='adminUser.student'),
        ),
    ]
