# Generated by Django 4.0.2 on 2022-04-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUser', '0006_alter_attendance_stud_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(to='adminUser.Subject'),
        ),
    ]
